#! /bin/bash
#TO TEST THE SHIFT COMMAND

while [ $# -gt 0 ]
do
	for i in $@ 
	do
	      ((j++))
		      echo "$i = \$$j"
	                  
	done

	
	case $1 in
	-a|--valueA)  valA="$2" 
	      shift  ;;
	-b|--valueB) valB="$2"
	      shift  ;;
	--help|*) echo "USAGE:"
		 echo "      --valueA: \"valueA\""
		 echo "      --valueB: \"valueB\""
		 echo "      --help" 
		 exit 1   ;;

	   esac

     

done

echo "A: $valA"
echo "B: $valB"

