#! /bin/bash

#ThIS IS A SCRIPTS WHICH TAKES ANY NUMBER OF DESIRED INTEGER INPUTS AND CALCULATE THE SUM OF THE SQUARES OF ALL THE INPUT ARGUMEBR AS WELL AS THE TOTAL NUMBER OF ARGUMENT INPUTED

count=0
sum=0

for x in "$@"
do
	if ! [[ "$x" =~ ^[0-9]+$ ]]
	then
		echo invalid input: pls input integer argument
		exit 1

	else
		p=$((x*x))
		sum=$((sum+p))
		count=$((count+1))
	fi
done

avg=$((sum/count))

echo "the total number of input argument is $count"
echo "the sum of their squares is $sum"
echo "The average of their square  is $avg"

