#! /bin/bash

green_text=32
bg_black=40
echo -e "\033[${bg_black};${green_text}m"

echo "##########################################"
echo "SCRIPT TO CHANGE MY BACKGROUND COLOR TO BLACK AND MY TEXT COLOR TO GREEN"
echo "##########################################"
exit 0
shift
if ls
then
	echo -e "033\[${bg_black};${green_text}m"
fi



