#! /bin/bash

red_text=31
bg_black=40
echo -e "\033[${bg_black};${red_text}m"

echo "##########################################"
echo "SCRIPT TO CHANGE MY BACKGROUND COLOR TO BLACK AND MY TEXT COLOR TO RED"
echo "##########################################"
exit
if ls
then
	echo -e "033\[${bg_black};${green_text}m"
fi



