#! /bin/bash

yellow_text=33
bg_black=40
echo -e "\033[${bg_black};${yellow_text}m"

echo "##########################################"
echo "SCRIPT TO CHANGE MY BACKGROUND COLOR TO BLACK AND MY TEXT COLOR TO YELLOW"
echo "##########################################"
exit
if ls
then
	echo -e "033\[${bg_black};${green_text}m"
fi



