#! /bin/bash
# SECOND PROJECT TO DEVELOP A CHESSBOARD WITH ANY CHOICE OF COLOR

#ASSIGN WITH AND HEIGHT
read -p "Entet cell's width: " wi
echo
read -p "Enter cell's height: " ht
echo
[[ "$wi" =~ ^[0-9]+$ ]] && [[ "$ht" =~ ^[0-9]+$ ]] || { echo "invalid input, pls enter an integer"; exit; }    

#ASSIGN PLAYER COLORS
echo
echo "##########################################"
echo
PS3="Pls choose player1's color: "
select color1 in red green yellow blue purple cyan white black; do
case $color1 in
red) echo "you have chosen playe1's color as $color1"
              let color1=1
         break  ;;
green) echo "you have chosen player1's color as $color1"
              let color1=2
         break  ;;
yellow) echo "you have chosen ppayer1\'s color as $color1"
              let color1=3
         break  ;;
blue) echo "you have chosen player1's color as $color1"
              let color1=4
         break  ;;
purple) echo "you have chosen player1's color as $color1"
              let color1=5
         break  ;;
cyan) echo "you have chosen player1's color as $color1"
              let color1=6
          break  ;;
white) echo "you have chosen player1's color as $color1"
               let color1=7
          break  ;;
black) echo "you have chosen player1's color as $color1"
	let color1=0
	break    ;;
*)    echo "No color match found; try again"    ;;
    esac
done
echo ""
echo "##########################################"
PS3="Pls choose player2's color: "
select color2 in red green yellow blue purple cyan white black; do
case $color2 in
red) echo "you have chosen player2's color as $color2"
	let color2=1
	break  ;;
green) echo "you have chosen player2's color as $color2"
	let color2=2
	break  ;;
yellow) echo "you have chosen player2's  olor as $color2"
	let color2=3
	break  ;;
blue) echo "you have chosen player2's color as $color2"
	let color2=4
	break  ;;
purple) echo "you have chosen player2's color as $color2"
	let color2=5
	break  ;;
cyan) echo "you have chosen player2's color as $color2"
	let color2=6
	break  ;;
white) echo "you have chosen player2's color as $color2"
	let color2=7
	break  ;;
black) echo "you have chosen player2's color as $color2"
	let color2=0
	break  ;;
*) echo "No color match found;try again"     ;;
          esac
    done
echo ""
echo "##########################################"
#NOW PRINT THE CHESSBOARD
for i in $(seq 1 8 )
do
if [ $[i%2] -eq 1 ]
then
	for j in $(seq $ht )
	do
		for k in $(seq 1 8 )
		do
			if [ $[k%2] -eq 1 ]
				then
echo -e "\033[1;4${color1}m`printf "%${wi}s"`\033[0m\c"
else
echo -e "\033[1;4${color2}m`printf "%${wi}s"`\033[0m\c"
			fi
			let k++
		done
		let j++
	done
	for j in $(seq $ht )
	do
		for k in $(seq 1 8 )
		do
			if [ $[k%2] -eq 1 ]
			then
echo -e "\033[1;4${color2}m`printf "%${wi}s"`\033[0m\c"
echo -e "\033[1;4${color1}m`printf "%${wi}s"`\033[0m\c"
			fi
			let k++
		done
		let j++
	done
    fi
let i++
done
printf "\n"
	

