#! /bin/bash
#chessboard development
read -p "set chessboard cell's width(two cells width space as one unit):" width
if [[ $width =~ "^[0-9]+$" ]]
then
	echo "wrong choice of width, pls check your choice and try again"
   exit
fi
#select width
let width=$width*2

#select player


#select players color
echo "###########################################"
echo

PS3="What color do u want for player1: "
select choice in red green yellow blue purple cyan white; do
case $reply in
	$reply)  
		echo -n "player1\'s color is $color1"
		let color1=$reply
			break 
			;;
	            esac
               done
	echo
echo "###################################2#######"
echo

PS3="What color do u want for player2: "
select choice in red green yellow blue purple cyan white; do
case $reply in
	$reply) 
		echo  "player2\'s color is $color2"
		let color2=$reply
			break
			;;
	          esac
        done
  echo
echo "###########################################"
echo
if [[ color1 == color2 ]]
then
	echo "The color of the two players cannot be the same, pls check your input and try again"
	exit
fi
   
 # Now print the chessboard   
 for i in $(seq 1 4 )
 do
	 let w=$(((width)/2))
	 for j in $(seq 1 $w )
	 do
		 for k in $(seq 1 4 )
		 do
		  echo -e "\e[4${color1}m$(printf %${width}s)\e[0m\c"
		   echo -e "\e[4${color2}m$(printf %${width}s)\e[0m\c"
		 done
             echo
	 done
	 for j in $(seq 1 $w )
	 do
		 for k in $(seq 1 4 )
		 do
	         echo -e "\e[4${color2}m$(printf %${width}s)\e[0m\c"
		  echo -e "\e[4${color1}m$(printf %${width}s)\e[0m\c"
		 done
	     echo
	 done
 done
			 
