#! /bin/bash
#program to print a chessboard and assign it desired colors
clear='\033[0m'
white='\033[0;47m'
black='\033[0;40m'
for i in $(seq 1 9 )
do
    for j in $(seq 1 9 )
    do
        printf "carmel \t"
   done
 echo 
done
