#! /bin/bash

#PROGRAM TO GREET A PERSON (WHO NAME IS PROVIDED) TO A GIVEN NUMBER OF TIMES

NAME=""
TIME=1
#FUNCTION DECLARATION
USAGE(){
	printf "Usage:\n        /.$0 [ -n name] [ -t k ] where k is a positive integer i.e 1,2,3,...,etc" 1>&2
       } 
abnormal_exit(){
		     USAGE
	             exit 1
	       }

while getopts ":n:t:" opt
do
	case "${opt}" in
		n) NAME=${OPTARG}  ;;
		t) TIME=${OPTARG}
			num='^[0-9]+$'
			if ! [[ $TIME =~ $num ]]
			then
			     echo "E: insert a positive integer after -t flag"
			     abnormal_exit

			elif [ $TIME -eq 0 ]
			then
				echo "E:time cannot be zero: pls enter a positve integer"
			abnormal_exit
	                fi           ;;

		:) echo "E:_${OPTARG} mising: pls parse an argument to n"
	              abnormal_exit  ;;
		*) abnormal_exit     ;;
	esac
done

	if [ -z "$NAME" ]
	then
		STRING="Hi"
	else
		STRING="Hi, $NAME"
	fi
              
	      count=1
	      while [ $count -le $TIME ]
	     
	      do
		    echo "$STRING"

		    let   count+=1
	      done
printf "\n"
exit 0

