#! /bin/bash

#A PROGRAM TO PING THE IP ADDRESS A PORT OF A WEBSITE

USAGE(){
	   printf "Usage:\n     ./$0 -[nt[i|p]v]"
	   exit 1
   }     
while getopts ":nti:p:v" opt
do
	case ${opt} in
		i) ip=${OPTARG}   ;;
		p) port=${OPTARG} ;;
                n) nmap_yes=1     ;;
		t) ping_yes=1     ;;
		*) USAGE          ;;
	esac
done
if [ ! -z "$nmap_yes" ] && [ $nmap_yes -eq 1 ]
then
	if [ ! -z "$ip" ] && [ ! -z "$port" ]
	then
		nmap -p "$ip" "$port"
	fi
fi

if [ ! -z "$ping_yes" ] && [ $ping_yes -eq 1 ]
then
	if [ ! -z "$ip" ]
	then
		ping -c 5 "$ip"
	fi
fi
shift $((OPTIND-1))
if [ ! -z "$@" ]
then
echo "fancy arguments at the end: $@"
fi
