#! /bin/bash
PS3="pls choose an option: "
select option in "monday" "tuesday" "wednesday" "thursday"
do
case $option in
	${option}) echo "Name of day is $option"
		break   ;;
*) echo "No match found"            
	  break ;;
      esac
  done
