#! /bin/bash
PS3="pls choose an options: "
select option in monday tuesday wednesday thursday 
do
case $option in
monday) echo "Name of day is $option" 
        let $ption=2 
	continue        ;;
tuesday) echo "Name of day is $option" 
	let $option=2
	continue        ;;
wednesday) echo "Name of day is $option"
	let $option=3
	continue        ;;
thursday) echo "Name of day is $option"
	let $option=4
	continue        ;;
*) echo "No match found"                 
	  break ;;
      esac
done
