#! /bin/bash
for i in  123 qag 1wb 123974856 .189 '^[0-9]+$' '134. 567'
do
        printf "\n Testing $i: "
	if [[ $i =~ ^[0-9]+$ ]]
	then
	printf "$i confirmed and matched"
        else
	    printf ""
	fi
done
printf "\n"

