#! /bin/bash
echo "total no. of args = $#"
echo "the args are: $*"
for i in $(seq 0 7)
do 
echo "======================================="
echo "for shift $i"
echo the first arg argument after shift $i is:$1
echo the second argument after shift $i is:$2
echo the third argument after shift $i is: $3
shift
done
echo "======================================="
echo "$0 is \$0"
