#! /bin/bash

#THIS PROGRAM WILL PRINT OUT THE INPUTED ARGUMENT IN INCREASING ORDER OF MAGNITUDE
echo "Enter three numbers"
read a; read b; read c

if [ $a -le $b -a $b -le $c ]
then
	echo "$a $b $c"


elif [ $a -le $c -a $c -le $b ]
then
	echo "$a $c $b"


elif [ $b -le $c -a $c -le $a ]
then                                              echo "$b $c $a"


elif [ $b -le $a -a $c -le $c ]
then                                              echo "$b $a $c"                   


elif [ $c -le $b -a $b -le $a ]
then
	echo "$c $b $a"                   


else                                             echo "$c $a $b"                   
fi
