#! /bin/bash

#THIS PROGRAM WILL PRINT OUT THE INPUTED ARGUMENT IN INCREASING ORDER OF MAGNITUDE

echo "pls enter three integer numbers: "
read a; read b; read c



if [ $a -gt $b ]
then
	echo "$b $a $c"

else
	echo "$a $b $c"
	
if [ $a -gt $c ]
then
	echo "$c $a $b"

else
	echo "$a $c $b"

if [ $b -gt $c ]
then
	echo "$c $b $a"

else
	echo "$b $c $a"

       fi
    fi
fi

