#! /bin/bash

#PROGRAM TO COUNT THE NUMBER OF SUDO LINES  IN A LOGFILE
no_open=0
open(){
	  echo "the number of words starting wirh e  is $no_open"
      }

trap open USR1

while read line

do
	if [[ "$line" =~ [^0-9] ]]

	then
	let	no_open++
	fi
done < chessboard
