#! /bin/bash

#PROGRAM TO COUNT THE NUMBER OF SUDO LINES  IN A LOGFILE
no_open=0
opem(){
	  echo "the number of words starting wirh e  is $no_open"
      }

trap opem USR1

while read line

do
	if [[ "$line" =~ [^e] ]]

	then
echo $line	
	let	no_open++
	fi
done < chessboard
