#! /bin/bash

#PROGRAM TO GENERATE AN INFINITE AND THEN  EXIT OR INTERUPT IT WITH THE TRAP COMMAND

func(){

         if SIGTERM
         then
              trap " " SIGINT
	      echo "you have sent a sigterm signal"

         elif SIGINT
         then
	     trap " " SIGTERM
	     echo "you have sent a sigint signal"
         exit
	 
	 fi
  }

trap func SIGINT SIGTERM

echo "press ctrl+Z to terminate or ctrl+C  to interrupt the programm"

i=1
while :

do
	echo "the $ith program is $i"
	((i++))
done
