#! /bin/bash

#PROGRAM TO COUNT THE NUMBER OF SUDO LINES  IN A LOGFILE
no_open=0
open(){
	  echo "the number of  sudo session  is $no_open"
      }

trap open USR1

sudo chessboard -f | while read line
do
	if [[ "$line" =~ sudo .*session.*opened ]]
	then
		no_open=$((no_open+1))
	fi
done
